<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link href="https://fonts.googleapis.com/css?family=Italiana|Nunito" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Italiana" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="public/style.css">
		<link href="https://fonts.googleapis.com/css?family=Cinzel|Griffy" rel="stylesheet">
		<script type="text/javascript" src="public/script/script.js"></script>
		<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
 		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<title>Recherche books</title>
	</head>
	<body>
		<?php require('apps/search_elem.php'); ?>
		<?php require('apps/search.php'); ?>
	</body>
</html>