<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link href="https://fonts.googleapis.com/css?family=Italiana|Nunito" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Italiana" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<script type="text/javascript" src="public/script/jquery-3.1.1.min.js"></script>
		<script type="text/javascript" src="public/script/bootstrap.min.js"></script>
		<script type="text/javascript" src="public/script/script.js"></script>
		<title>Recherche</title>
	</head>
	<body>
		<?php require('apps/search.php'); ?>
	</body>
</html>